minimumFee:
  NFT: '1ce1ea41ceaed94a6976a047645ffb3f3da3916685268c8f2d8f80f892147caa'
  minimumFeeAddress: '9fmj8dX6QFy9PS2zCqYJj4LTyDvWRS29BBuSTToy961oWf2VaQQ'
  feeAddress: '9gPqDuyxpmV2bR62zdbgxuvJAahDUpnaZw8Srv2JYHauAiHZEb4'
  fetchBoxRetry: 3
  rsnRatioPrecision: 6
  bitcoinTxVSize: 150
  ethereumTxFee: 0.001
  supportedTokens:
    - tokenId: 'erg'
      ergoSideTokenId: 'erg'
      name: 'ERG'
      decimals: 9
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'ergo'
      fee:
        delays:
          ergo: 5
          cardano: 30
          bitcoin: 2
          ethereum: 50
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
        bitcoinConfirmation: 6
tokensPath: './config/rosen/tokens.json' # path to supported tokens of bridge
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'debug'
  - type: 'console'
    level: 'info'
triggerPercent:
  bridgeFee: 10
  rsnRatio: 10
  bitcoinNetworkFee: 100
  cardanoNetworkFee: 30
  ergoNetworkFee: 50
  ethereumNetworkFee: 150
discordWebHookUrl: '' # Discord webhook url for sending notifications
interval: 14400 # every 4 hours
kv:
  restApiUrl: # Upstash URL
  restApiToken: # Upstash token
