urls:
  coinMarketCap: 'https://api.coinmarketcap.com'
  coingecko: 'https://api.coingecko.com'
  spectrum: 'https://api.spectrum.fi'
  dexHunter: 'https://api-us.dexhunterv3.app'
  ergoExplorer: 'https://api.ergoplatform.com'
  cardanoKoios: 'https://api.koios.rest/api/v1'
  bitcoinEsplora: 'https://mempool.space'
  ethereumRpc: 'https://eth-mainnet.public.blastapi.io'
  binanceRpc: 'https://bsc-mainnet.public.blastapi.io'
minimumFee:
  NFT: '1ce1ea41ceaed94a6976a047645ffb3f3da3916685268c8f2d8f80f892147caa'
  minimumFeeAddress: '9fmj8dX6QFy9PS2zCqYJj4LTyDvWRS29BBuSTToy961oWf2VaQQ'
  feeAddress: '9gPqDuyxpmV2bR62zdbgxuvJAahDUpnaZw8Srv2JYHauAiHZEb4'
  fetchBoxRetry: 3
  rsnRatioPrecision: 6
  bitcoinTxVSize: 150
  ethereumTxFee: 0.001
  binanceTxFee: 0.0001
  defaultFee:
    delays:
      ergo: 5
      cardano: 30
      bitcoin: 2
      ethereum: 50
      binance: 200
    bridgeFeeUSD: 10
    ergNetworkFee: 0.0013
    adaNetworkFee: 3.4
    feeRatioFloat: 0.005
    bitcoinConfirmation: 6
  supportedTokens:
    - tokenId: ''
      ergoSideTokenId: ''
      name: ''
      decimals: 0
      priceBackend: ''
      priceBackendParams: # depends on priceBackend
        network: ''
      fee: # will use defaultFee if this is not provided
        delays:
          ergo: 5
          cardano: 30
          bitcoin: 2
          ethereum: 50
          binance: 200
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
        bitcoinConfirmation: 6
tokensPath: './config/rosen/tokens.json' # path to supported tokens of bridge
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'debug'
  - type: 'console'
    level: 'info'
triggerPercent:
  bridgeFee: 10
  rsnRatio: 10
  bitcoinNetworkFee: 100
  cardanoNetworkFee: 30
  ergoNetworkFee: 50
  ethereumNetworkFee: 150
  binanceNetworkFee: 50
discordWebHookUrl: '' # Discord webhook url for sending notifications
interval: 14400 # every 4 hours
kv:
  restApiUrl: # Upstash URL
  restApiToken: # Upstash token
