minimumFee:
  NFT: '405cb1483b46340ee1a111aa42eaaffa53451cab3220fe9deb752a03f2ab0b85'
  V1NFT: '05690d3e7a8daae13495b32af8ab58aaec8a5435f5974f6adf17095d28cac1f5'
  minimumFeeAddress: '9fmj8dX6QFy9PS2zCqYJj4LTyDvWRS29BBuSTToy961oWf2VaQQ'
  feeAddress: '9eedUp4SDLsgxBiPJid55qUnCRDuXeNs1Z9fpi4vZtPgZcaBgzL'
  supportedTokens:
    - tokenId: 'erg'
      ergoSideTokenId: 'erg'
      name: 'ERG'
      decimals: 9
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'ergo'
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: 'ada'
      ergoSideTokenId: 'e023c5f382b6e96fbd878f6811aac73345489032157ad5affb84aefd4956c297'
      name: 'ADA'
      decimals: 6
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'cardano'
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b'
      ergoSideTokenId: '8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b'
      name: 'RSN'
      decimals: 3
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'debug'
  - type: 'console'
    level: 'info'
triggerPercent:
  bridgeFee: 10
  cardanoNetworkFee: 10
  ergoNetworkFee: 10
discordWebHookUrl: 'https://discord.com/api/webhooks/1182973774237274213/8mnQgzLzaxpKEupVS0sUR_sjLVEioWkWhkXFJmCnQOx2XO9bfOnTxKuQ_up9OD87MgQP' # Discord webhook url for sending notifications
interval: 14400 # every 4 hours
