minimumFee:
  NFT: '1ce1ea41ceaed94a6976a047645ffb3f3da3916685268c8f2d8f80f892147caa'
  minimumFeeAddress: '9fmj8dX6QFy9PS2zCqYJj4LTyDvWRS29BBuSTToy961oWf2VaQQ'
  feeAddress: '9gPqDuyxpmV2bR62zdbgxuvJAahDUpnaZw8Srv2JYHauAiHZEb4'
  supportedTokens:
    - 'erg'
    - 'ada'
    - '8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b'
    - '03faf2cb329f2e90d6d23b58d91bbb6c046aa143261cc21f52fbe2824bfcbf04'
    - '003bd19d0187117f130b62e1bcab0939929ff5c7709f843c5c4dd158949285d0'
logs:
  maxSize: 20m
  maxFilesCount: 14d
  path: ./logs/
  level: debug
fee:
  ergoHeightDelay: 0
  cardanoHeightDelay: 0
  bridgeFeeUSD: 10
  ergNetworkFee: 0.0013
  adaNetworkFee: 3.4
  feeRatioFloat: 0.005
triggerPercent:
  bridgeFee: 10
  cardanoNetworkFee: 10
  ergoNetworkFee: 10
discordWebHookUrl: '' # Discord webhook url for sending notifications
