minimumFee:
  NFT: '405cb1483b46340ee1a111aa42eaaffa53451cab3220fe9deb752a03f2ab0b85'
  V1NFT: 'e2ed4d64393222db666f20e67803e9e6fbe6d64531e14ff52ddd95615b0cbf17'
  minimumFeeAddress: '9hPNftibHVKpDmgKj5acaN4xurK1uCqVJJEPPFrZuP3wUD6Dz7r'
  feeAddress: '9eedUp4SDLsgxBiPJid55qUnCRDuXeNs1Z9fpi4vZtPgZcaBgzL'
  supportedTokens:
    - tokenId: 'erg'
      ergoSideTokenId: 'erg'
      name: 'ERG'
      decimals: 9
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'ergo'
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: 'ada'
      ergoSideTokenId: 'e023c5f382b6e96fbd878f6811aac73345489032157ad5affb84aefd4956c297'
      name: 'ADA'
      decimals: 6
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'cardano'
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b'
      ergoSideTokenId: '8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b'
      name: 'RSN'
      decimals: 3
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '0cd8c9f416e5b1ca9f986a7f10a84191dfb85941619e49e53c0dc30ebf83324b'
      ergoSideTokenId: '0cd8c9f416e5b1ca9f986a7f10a84191dfb85941619e49e53c0dc30ebf83324b'
      name: 'COMET'
      decimals: 0
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: 'a0028f350aaabe0545fdcb56b039bfb08e4bb4d8c4d7c3c7d481c235.484f534b59'
      ergoSideTokenId: '6ad70cdbf928a2bdd397041a36a5c2490a35beb4d20eabb5666f004b103c7189'
      name: 'hosky'
      decimals: 0
      priceBackend: 'coingecko'
      priceBackendParams:
        network: 'hosky'
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '03faf2cb329f2e90d6d23b58d91bbb6c046aa143261cc21f52fbe2824bfcbf04'
      ergoSideTokenId: '03faf2cb329f2e90d6d23b58d91bbb6c046aa143261cc21f52fbe2824bfcbf04'
      name: 'SigUSD'
      decimals: 2
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '003bd19d0187117f130b62e1bcab0939929ff5c7709f843c5c4dd158949285d0'
      ergoSideTokenId: '003bd19d0187117f130b62e1bcab0939929ff5c7709f843c5c4dd158949285d0'
      name: 'SigRSV'
      decimals: 0
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
    - tokenId: '9a06d9e545a41fd51eeffc5e20d818073bf820c635e2a9d922269913e0de369d'
      ergoSideTokenId: '9a06d9e545a41fd51eeffc5e20d818073bf820c635e2a9d922269913e0de369d'
      name: 'SPF'
      decimals: 6
      priceBackend: 'spectrum'
      priceBackendParams: {}
      fee:
        ergoHeightDelay: 0
        cardanoHeightDelay: 0
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'debug'
  - type: 'console'
    level: 'info'
triggerPercent:
  bridgeFee: 10
  cardanoNetworkFee: 10
  ergoNetworkFee: 10
discordWebHookUrl: 'https://discord.com/api/webhooks/1182973774237274213/8mnQgzLzaxpKEupVS0sUR_sjLVEioWkWhkXFJmCnQOx2XO9bfOnTxKuQ_up9OD87MgQP' # Discord webhook url for sending notifications
interval: 14400 # every 4 hours
